### ISSUE TITLE
maintner-sprvsr: Use a Label for GitHub API Key Discovery

### ISSUE THREAD

**Issue by orthros** [GoogleCloudPlatform/devrel-services#14]
Currently `maintner-sprvsr` is given a name of a Kubernetes `Secret` in order to discover the set of GitHub API Tokens available to be vended to the individual workers. 

Rather than specify the name of a particular secret in the `Deployment`: prefer to specify the name of a `Label` in the `Deployment` so that `maintner-sprvsr` can better scale the Keys. 

This should also include a separate goroutine that periodically checks for the new Secrets with labels in the cluster to vend to the workers.

**Comment by jmdobry** [comment]
Obsolete as we're switching to authenticating as GitHub Apps.
