### ISSUE TITLE
core: repos serialization enhancements

### ISSUE THREAD

**Issue by orthros** [GoogleCloudPlatform/devrel-services#34]
Right now we are using a very naive approach to serializing and deserializing the list of repositories to track from GCS. We read in a JSON blob from GCS and manually parse it. This is inefficient and error prone.

The scope of this work would be to first take the `TrackedRepository` struct in  `repos/repos.go` and annotate it with JSON serialization metadata ([example](https://gobyexample.com/json)). 

The next step would be to take the code in `repos_bucket.go` and to replace the manual unmarshaling code with the standard library.

Finally, add unit tests for the marshaling and unmarshaling of the struct.

**Comment by Gabitchov** [comment]
Hello, I would like to help for this one!

**Comment by Gabitchov** [comment]
Is it possible to add some dependencies for testing. I think to a framework for mocking data. When I read the `repos_bucket.go` and the function `GetRepos`, it will be great to have something to mock the input parameter. WDYT?

**Comment by orthros** [comment]
Thanks for being interested in the project! 

I think when it comes to testing the `repos_bucket.go`, it would be okay to simply remove the manual unmarshaling code and add marshal tests elsewhere. 

The other option I see would be to use the [google-cloud-go-testing](https://github.com/googleapis/google-cloud-go-testing) package to mock out the Cloud Storage client dependency, but this has [the problem with mocks](https://testing.googleblog.com/2013/05/testing-on-toilet-dont-overuse-mocks.html) and the package  is currently in alpha. This path would require moving the instantiation of the Cloud Storage client to the `NewBucketRepo` function (which will need a `Context` passed to it), and have the client be a property of the `bucketRepoList` struct. 

For now it should be fine to not add tests to `repos_bucket.go`

**Comment by Gabitchov** [comment]
I initiated the work. I will look for the [google-cloud-go-testing](https://github.com/googleapis/google-cloud-go-testing) to see the way to add in my work. Do you have an easy way to test my work without unit test? For example, a minimal environment configuration to have.

**Comment by Gabitchov** [comment]
So I tried to use the library and, effectively, if we want to test with this one, we should change the design of `NewBucketRepo`  either injecting the Storage client or, like you explained, instantiating in constructor function. In both cases, the storage should be kept in the `bucketRepoList`. 

Finally, I removed the test of my work.
