### ISSUE TITLE
infra: Add a State Layer to samplr

### ISSUE THREAD

**Issue by orthros** [GoogleCloudPlatform/devrel-services#54]
> Engineering Protip: Make state someone else's problem.
[-James Ward](https://twitter.com/_JamesWard/status/1186787408584626179?s=20)

It is probably time to introduce some sort of state (read that as "database") to our solution.

Reasons to introduce a database:
* `samplrd` is the only "source of truth" for both reads and writes for Snippets. Should the pod go down (for whatever reason) requests for snippets will result in either errors or 0 snippets returned.
* Calculating snippets is time consuming, especially for larger repositories, this introduces an unnecessary lag during startup time.
* Proxying requests to individual pods requires:
  * Logic in the reverse proxy to query multiple orgs/repos
  * Individual worker pods to maintain pagination state for all incoming queries could cause them to be resource overloaded

### Relational:

There are some good arguments for using a Relational database:
* Relatively familiar for most developers.
* Huge swathes of documentation
* Google Cloud offers a hosted MySQL solution (helps reduce ops cost)
* Rigidly Structured Data

### Graph DB

There are two main arguments for using a Graph DB:
* Exposing an API on top of this data via GraphQL would mimic the behaivour of the v4 GitHub API, (which our users are presumably familiar with, or are interestd in migrating to)
* The data stored is a directed acyclic graph, which Graph DBs are great at storing.
  * In fact, it comes to mind that samplr could be rearchitected to be an updater of commits on a GraphDB, with a periodic job (or trigger) which calculates and updates snippets from within the DB itself, and a GraphQL API on top of the database.

**Comment by orthros** [comment]
cc @jmdobry

**Comment by jmdobry** [comment]
Is this scoped to Samplr only or do we want a single holder of state for all of devrel-service? If we have a single source of state, then we could more easily consolidate down to a single gRPC service on top of the state for all the maintnr/samplr read RPCs, and the data gathering workers can be more separate from the API concerns.

**Comment by orthros** [comment]
Good question and point. 

The initial scope of this is for Samplr alone. Maintner already has a "state" layer with the GCS logs. Adding a read only mode for said logs would be possible, and would allow us to do rolling upgrades more smoothly.

That said, there would be nothing wrong with what you're suggesting.

**Comment by orthros** [comment]
Been doing some more research and thinking on this. Relational is likely the way to go, but I'm still mostly convinced that a GraphDB would be a good fit for samplr.

**Comment by orthros** [comment]
Final note before I start writing up table schemas:

maintner would be served well by a document DB, but we would be duplicating far too much data for it to be scaleable in samplr.

**Comment by jmdobry** [comment]
Seems like duplication would be eliminated by using relational for both?

**Comment by orthros** [comment]
Yep agreed. I'm moving forward on a relational db for this
